---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/en/testimonial.yml
  label: Data- testimonials
  match: "**/*"
- type: document
  path: data/en/team.yml
  label: Data-team
  match: "**/*"
- type: document
  path: data/en/skill.yml
  label: Data-skill
  match: "**/*"
- type: document
  path: data/en/satisfiedClients.yml
  label: Data-satisfied client
  match: "**/*"
- type: document
  path: data/en/project.yml
  label: Data-project
  match: "**/*"
- type: document
  path: data/en/pricing.yml
  label: Data-Pricing
  match: "**/*"
- type: document
  path: data/en/mission.yml
  label: Data- Mission
  match: "**/*"
- type: document
  path: data/en/heroSlider.yml
  label: Data- hero slider
  match: "**/*"
- type: document
  path: data/en/contact.yml
  label: data-contact
- type: document
  path: data/en/about.yml
  label: data-about
- type: document
  path: config.toml
  label: configuration
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
- type: directory
  path: content/service
  label: Service
  create: all
  match: "**/*"
- type: directory
  path: content/project
  label: Project
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/pricing
  label: Pricing
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.57.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.57.1
